### ISSUE TITLE
[P1] TypeError: Object of type type is not JSON serializable

### ISSUE THREAD

**Issue by srn-source** [stanfordnlp/pyreft#69] opened 2024-04-28 15:24 UTC
I try to run train.py of alpaca examples with  " TinyLlama/TinyLlama-1.1B-Chat-v1.0" but i got this error before training.

![image](https://github.com/stanfordnlp/pyreft/assets/107049099/75232f1d-6a73-4ecc-ad6a-4504e19f4de5)

what should i do? please guide me.
I am searching for it, i think it is about model.config cannot convert to json? i am not sure

**Comment by PinetreePantry** [comment] 2024-04-28 19:15
Could you paste here the command or the script that you are running? I think the issue is related to Pyvene unable to serialize the config of the model that you are using

**Comment by srn-source** [comment] 2024-04-28 19:50
@PinetreePantry  i use the same in readme demo.

python train.py --model_name_or_path  TinyLlama/TinyLlama-1.1B-Chat-v1.0 \
	--data_path ./alpaca_data.json \
	--output_dir ./test/ \
	--layers "8;19" \
	--rank 4 \
	--position "f1+l1" \
	--num_train_epochs 1 \
	--per_device_train_batch_size 4 \
	--per_device_eval_batch_size 4 \
	--gradient_accumulation_steps 8 \
	--evaluation_strategy "no" \
	--save_strategy "no" \
	--learning_rate 2e-5 \
	--weight_decay 0. \
	--warmup_ratio 0.03 \
	--lr_scheduler_type "cosine" \
	--logging_steps 1

**Comment by frankaging** [comment] 2024-04-29 06:13
hey @srn-source, please try to add `--report_to none` and rerun. Thanks!

**Comment by srn-source** [comment] 2024-04-29 06:49
@frankaging  Its work, what happen? but thank you so much.

**Comment by PinetreePantry** [comment] 2024-04-29 07:39
I think the reason might be because you accidentally enabled (probably by default) tensorboard logging, which triggered [this line](https://github.com/huggingface/transformers/blob/73014b561d5f88d728e46a57d346f516fefe3f2d/src/transformers/integrations/integration_utils.py#L646) in the transformers library code. This would require a serialization of the Pyvene model's configs. Our model's configs contain [types](https://github.com/stanfordnlp/pyvene/blob/main/pyvene/models/configuration_intervenable_model.py#L68), not serializable by json.

**Comment by frankaging** [comment] 2024-04-29 18:34
Marking this as close, and will track the progress in https://github.com/stanfordnlp/pyreft/issues/70

**Closed by frankaging** 2024-04-29 18:34 UTC
Labels: question

**Comment by Shigerello** [comment] 2024-06-13 03:16
> please try to add `--report_to` none and rerun. Thanks!

Below is another workaround in a Python code snippet. This approach prevents TensorBoard logging from attempting to serialize the Pyvene model's configs, which cannot be serialized due to the use of `type`.

```python
from transformers.integrations.integration_utils import TensorBoardCallback
trainer.remove_callback(TensorBoardCallback)
```
